---
- name: Install zabbix-agent
  apt:
    name: zabbix-agent
    update_cache: yes

- name: Template agentd.conf
  template:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf

- name: Upping zabbix
  shell:
    cmd: service zabbix-agent restart