---
- name: Mkdir zabbix
  file:
    path: /opt/zabbix
    state: directory

- name: Mkdir zabbix
  file:
    path: /opt/zabbix/src
    state: directory

- name: Mkdir zabbix
  file:
    path: /opt/zabbix/src/mysql
    state: directory

- name: Copy compose
  copy:
    src: files/docker-compose.yml
    dest: /opt/zabbix

- name: Upping zabbix
  shell:
    cmd: docker-compose up -d
    chdir: /opt/zabbix/